// <auto-generated />
namespace Flos_Blog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class stats_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stats_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201703081446184_stats_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
